spring:
  datasource:
    url: jdbc:mysql://$(DB-Url):3306/$(DB-Name)?useSSL=true
    username: $(DB-Username)
    password: $(DB-Password)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 8080


azure:
  key-vault:
    enabled: true
    uri: https://shopticket.vault.azure.net/
    client-id: 35b9a723-7f30-4c1c-8a0d-15b6a0300554
    tenant-id: 2fcfe26a-bb62-46b0-b1e3-28f9da0c45fd
