spring:
  datasource:
    url: jdbc:mysql://shopticket.mysql.database.azure.com:3306/shop_ticket?useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 8080