spring:
  datasource:
    url: jdbc:mysql://shopticket.mysql.database.azure.com:3306/shopticketdb?useSSL=true
    username: martina
    password: Casola7.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 8080